In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
ds = pd.read_csv("CO2 PPM.csv")
ds

           Date  Decimal Date  Interpolated   Trend  Number of Days  Average
0    01-03-1958      1958.208        315.71  314.62              -1   315.71
1    01-04-1958      1958.292        317.45  315.29              -1   317.45
2    01-05-1958      1958.375        317.50  314.71              -1   317.50
3    01-06-1958      1958.458        317.10  314.85              -1   317.10
4    01-07-1958      1958.542        315.86  314.98              -1   315.86
5    01-08-1958      1958.625        314.93  315.94              -1   314.93
6    01-09-1958      1958.708        313.20  315.91              -1   313.20
7    01-10-1958      1958.792        312.66  315.61              -1   312.66
8    01-11-1958      1958.875        313.33  315.31              -1   313.33
9    01-12-1958      1958.958        314.67  315.61              -1   314.67
10   01-01-1959      1959.042        315.62  315.70              -1   315.62
11   01-02-1959      1959.125        316.38  315.88              -1   316.38
12   01-03-1959      1959.208        316.71  315.62              -1   316.71
13   01-04-1959      1959.292        317.72  315.56              -1   317.72
14   01-05-1959      1959.375        318.29  315.50              -1   318.29
15   01-06-1959      1959.458        318.15  315.92              -1   318.15
16   01-07-1959      1959.542        316.54  315.66              -1   316.54
17   01-08-1959      1959.625        314.80  315.81              -1   314.80
18   01-09-1959      1959.708        313.84  316.55              -1   313.84
19   01-10-1959      1959.792        313.26  316.19              -1   313.26
20   01-11-1959      1959.875        314.80  316.78              -1   314.80
21   01-12-1959      1959.958        315.58  316.52              -1   315.58
22   01-01-1960      1960.042        316.43  316.51              -1   316.43
23   01-02-1960      1960.125        316.97  316.47              -1   316.97
24   01-03-1960      1960.208        317.58  316.49              -1   317.58
25   01-04-1960      1960.292        319.02  316.86              -1   319.02
26   01-05-1960      1960.375        320.03  317.24              -1   320.03
27   01-06-1960      1960.458        319.59  317.36              -1   319.59
28   01-07-1960      1960.542        318.18  317.30              -1   318.18
29   01-08-1960      1960.625        315.91  316.92              -1   315.91
..          ...           ...           ...     ...             ...      ...
697  01-04-2016      2016.292        407.45  404.65              25   407.45
698  01-05-2016      2016.375        407.72  404.40              29   407.72
699  01-06-2016      2016.458        406.83  404.53              26   406.83
700  01-07-2016      2016.542        404.41  404.03              28   404.41
701  01-08-2016      2016.625        402.27  404.18              23   402.27
702  01-09-2016      2016.708        401.05  404.56              24   401.05
703  01-10-2016      2016.792        401.59  404.89              29   401.59
704  01-11-2016      2016.875        403.55  405.53              27   403.55
705  01-12-2016      2016.958        404.45  405.11              30   404.45
706  01-01-2017      2017.042        406.17  405.88              26   406.17
707  01-02-2017      2017.125        406.46  405.68              26   406.46
708  01-03-2017      2017.208        407.22  405.73              23   407.22
709  01-04-2017      2017.292        409.04  406.25              25   409.04
710  01-05-2017      2017.375        409.69  406.36              27   409.69
711  01-06-2017      2017.458        408.88  406.58              26   408.88
712  01-07-2017      2017.542        407.12  406.74              28   407.12
713  01-08-2017      2017.625        405.13  407.04              29   405.13
714  01-09-2017      2017.708        403.37  406.88              26   403.37
715  01-10-2017      2017.792        403.63  406.93              27   403.63
716  01-11-2017      2017.875        405.12  407.09              26   405.12
717  01-12-2017      2017.958        406.81  407.47              31   406.81
718  01-01-2018      2018.042        407.96  407.67              29   407.96
719  01-02-2018      2018.125        408.32  407.54              28   408.32
720  01-03-2018      2018.208        409.41  407.92              30   409.41
721  01-04-2018      2018.292        410.24  407.45              21   410.24
722  01-05-2018      2018.375        411.24  407.91              24   411.24
723  01-06-2018      2018.458        410.79  408.49              29   410.79
724  01-07-2018      2018.542        408.71  408.32              27   408.71
725  01-08-2018      2018.625        406.99  408.90              30   406.99
726  01-09-2018      2018.708        405.51  409.02              29   405.51

[727 rows x 6 columns]

In [3]:
x = ds.iloc[:,0:5]
x

           Date  Decimal Date  Interpolated   Trend  Number of Days
0    01-03-1958      1958.208        315.71  314.62              -1
1    01-04-1958      1958.292        317.45  315.29              -1
2    01-05-1958      1958.375        317.50  314.71              -1
3    01-06-1958      1958.458        317.10  314.85              -1
4    01-07-1958      1958.542        315.86  314.98              -1
5    01-08-1958      1958.625        314.93  315.94              -1
6    01-09-1958      1958.708        313.20  315.91              -1
7    01-10-1958      1958.792        312.66  315.61              -1
8    01-11-1958      1958.875        313.33  315.31              -1
9    01-12-1958      1958.958        314.67  315.61              -1
10   01-01-1959      1959.042        315.62  315.70              -1
11   01-02-1959      1959.125        316.38  315.88              -1
12   01-03-1959      1959.208        316.71  315.62              -1
13   01-04-1959      1959.292        317.72  315.56              -1
14   01-05-1959      1959.375        318.29  315.50              -1
15   01-06-1959      1959.458        318.15  315.92              -1
16   01-07-1959      1959.542        316.54  315.66              -1
17   01-08-1959      1959.625        314.80  315.81              -1
18   01-09-1959      1959.708        313.84  316.55              -1
19   01-10-1959      1959.792        313.26  316.19              -1
20   01-11-1959      1959.875        314.80  316.78              -1
21   01-12-1959      1959.958        315.58  316.52              -1
22   01-01-1960      1960.042        316.43  316.51              -1
23   01-02-1960      1960.125        316.97  316.47              -1
24   01-03-1960      1960.208        317.58  316.49              -1
25   01-04-1960      1960.292        319.02  316.86              -1
26   01-05-1960      1960.375        320.03  317.24              -1
27   01-06-1960      1960.458        319.59  317.36              -1
28   01-07-1960      1960.542        318.18  317.30              -1
29   01-08-1960      1960.625        315.91  316.92              -1
..          ...           ...           ...     ...             ...
697  01-04-2016      2016.292        407.45  404.65              25
698  01-05-2016      2016.375        407.72  404.40              29
699  01-06-2016      2016.458        406.83  404.53              26
700  01-07-2016      2016.542        404.41  404.03              28
701  01-08-2016      2016.625        402.27  404.18              23
702  01-09-2016      2016.708        401.05  404.56              24
703  01-10-2016      2016.792        401.59  404.89              29
704  01-11-2016      2016.875        403.55  405.53              27
705  01-12-2016      2016.958        404.45  405.11              30
706  01-01-2017      2017.042        406.17  405.88              26
707  01-02-2017      2017.125        406.46  405.68              26
708  01-03-2017      2017.208        407.22  405.73              23
709  01-04-2017      2017.292        409.04  406.25              25
710  01-05-2017      2017.375        409.69  406.36              27
711  01-06-2017      2017.458        408.88  406.58              26
712  01-07-2017      2017.542        407.12  406.74              28
713  01-08-2017      2017.625        405.13  407.04              29
714  01-09-2017      2017.708        403.37  406.88              26
715  01-10-2017      2017.792        403.63  406.93              27
716  01-11-2017      2017.875        405.12  407.09              26
717  01-12-2017      2017.958        406.81  407.47              31
718  01-01-2018      2018.042        407.96  407.67              29
719  01-02-2018      2018.125        408.32  407.54              28
720  01-03-2018      2018.208        409.41  407.92              30
721  01-04-2018      2018.292        410.24  407.45              21
722  01-05-2018      2018.375        411.24  407.91              24
723  01-06-2018      2018.458        410.79  408.49              29
724  01-07-2018      2018.542        408.71  408.32              27
725  01-08-2018      2018.625        406.99  408.90              30
726  01-09-2018      2018.708        405.51  409.02              29

[727 rows x 5 columns]

y = ds.iloc[:,5]
y

In [5]:
x = x.values
y = y.values

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_x = LabelEncoder()
x[:,0] = le_x.fit_transform(x[:,0])
x

array([[120, 1958.2079999999999, 315.71, 314.62, -1],
       [181, 1958.2920000000001, 317.45, 315.29, -1],
       [242, 1958.375, 317.5, 314.71, -1],
       ...,
       [424, 2018.5420000000001, 408.71, 408.32, 27],
       [485, 2018.625, 406.99, 408.9, 30],
       [546, 2018.7079999999999, 405.51, 409.02, 29]], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8, random_state = 42)

C:\Users\karthikram\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [15]:
from sklearn.linear_model import LinearRegression
LinReg = LinearRegression()
LinReg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [16]:
y_predict = LinReg.predict(x_train)
y_predict

array([326.05095228, 340.91724215, 313.33067518, 394.35929715,
       383.8990339 , 346.52053679, 336.10311205, 328.32446188,
       350.50928051, 325.78993432, 340.29739493, 397.45254215,
       316.9514479 , 323.19968863, 342.36007771, 316.8342847 ,
       355.56027297, 397.53607365, 345.90412932, 373.78438392,
       317.78294837, 353.76547032, 362.2315739 , 393.34576041,
       344.78957012, 364.62125962, 325.23248513, 319.54233731,
       320.80893716, 354.78306679, 378.73854934, 366.84303296,
       344.74556699, 341.02897294, 368.10840235, 396.83540321,
       387.84315822, 313.96251114, 345.15841071, 351.42639512,
       402.53356131, 320.57281471, 321.6265891 , 371.77878223,
       392.53454547, 316.0779201 , 380.09245418, 409.82564644,
       395.2919462 , 349.04899736, 332.69310588, 369.4902584 ,
       386.42491271, 357.88656075, 381.82904227, 352.86636267,
       332.04983053, 340.05973816, 359.37438265, 386.57723488,
       326.58455817, 338.20718735, 334.12153086, 375.82947232,
       333.73243857, 323.77490056, 359.15861937, 397.25043078,
       323.60797676, 355.57108487, 393.31336507, 369.05028166,
       380.35121784, 347.79963871, 346.77247093, 358.05846287,
       319.90179333, 319.36450676, 394.38223365, 382.17604483,
       395.78330618, 357.33877371, 318.98950099, 312.78767244,
       318.93164669, 377.84097441, 347.93806584, 365.94479293,
       376.70556022, 371.4789123 , 360.67015345, 332.34657864,
       322.94897931, 318.41318083, 315.48821281, 314.90453422,
       321.99628873, 327.72841202, 359.22713617, 391.84578557,
       316.29426675, 316.56115859, 347.2652701 , 392.22356172,
       328.60508142, 391.87425109, 364.18347033, 363.76797174,
       346.51525349, 372.46471127, 327.68025892, 388.65389811,
       390.21108672, 335.73528059, 343.88862625, 318.42852817,
       360.26737208, 337.59151729, 346.13990065, 341.34370277,
       390.20973103, 357.8713036 , 348.21472916, 358.1745347 ,
       355.46031448, 314.88874298, 334.92834813, 316.57328297,
       330.67636835, 390.95227235, 408.98957329, 402.88647322,
       382.9025629 , 331.47008208, 357.46881125, 319.58653285,
       349.17678786, 370.4270404 , 354.26146985, 338.55809239,
       331.02603303, 382.84524341, 346.17271873, 325.27067514,
       322.13060413, 353.26523514, 342.62636234, 317.25312285,
       358.47505348, 328.24358448, 336.08200079, 332.40435834,
       321.58243109, 389.54401298, 322.11726603, 322.13631873,
       382.39258951, 344.10887085, 334.93198391, 315.92511734,
       407.94068542, 345.90363566, 388.62642874, 351.45210339,
       343.13517427, 320.82537011, 335.00829345, 389.79923545,
       349.17752272, 339.24686718, 364.28900588, 327.01441196,
       359.58327559, 378.67705615, 392.94109253, 375.06705074,
       339.46714542, 368.32362908, 340.31564628, 344.06642222,
       318.06736229, 336.85311477, 332.27137052, 405.42271684,
       384.13837794, 322.62471651, 371.75433765, 378.3525998 ,
       352.44453123, 322.57741179, 351.20752352, 396.25249381,
       373.16680772, 403.5423139 , 329.66268001, 344.2523422 ,
       350.17364382, 395.50512775, 407.84854014, 324.7912362 ,
       324.31409341, 385.80500459, 386.73925749, 329.4045634 ,
       407.2773872 , 406.95081184, 353.75770835, 405.11380485,
       366.66507252, 344.76665042, 348.07807895, 396.85993189,
       325.10927552, 324.26101623, 361.72589897, 343.09331872,
       313.37983339, 328.19973992, 386.65042143, 345.57009889,
       401.33882932, 316.91949106, 342.27314396, 346.43660822,
       319.2736602 , 377.78967705, 329.90122955, 320.86193309,
       363.35407211, 334.41060294, 341.62623948, 365.18735979,
       337.25463244, 326.24251175, 320.45897844, 372.43868759,
       346.06820485, 341.73517126, 321.03116957, 365.88442674,
       326.40798236, 351.63830545, 355.71102713, 317.87993647,
       373.26850473, 328.91590514, 340.83581111, 314.97277094,
       363.25507365, 345.17157138, 339.38368176, 406.93779773,
       404.90951884, 329.40629484, 381.01315822, 390.07544902,
       359.39780671, 320.71889038, 330.4345097 , 345.34018533,
       366.70704286, 370.64181699, 395.15037526, 374.1631998 ,
       392.53277843, 362.1853012 , 315.116363  , 407.16139325,
       317.20751506, 355.9520261 , 374.61107733, 329.27904398,
       316.77429551, 319.87300773, 400.97060593, 397.36318818,
       317.38440895, 371.03780025, 393.6088845 , 345.58692409,
       395.12250635, 336.99506637, 322.5550508 , 339.92991625,
       368.71231235, 331.66832575, 320.31800019, 376.58886445,
       338.33490003, 321.28016426, 352.72688653, 336.24124621,
       319.72574471, 327.96053291, 333.63374473, 407.56393744,
       355.96405254, 352.86882234, 359.84592217, 325.09610817,
       388.05803443, 320.30077887, 372.19019813, 333.36569622,
       384.63046154, 393.09755316, 364.50170559, 368.12456556,
       371.04333035, 402.2424593 , 384.03770292, 391.19829361,
       316.07594769, 363.90140281, 327.87647807, 361.83314879,
       393.80293454, 323.39387156, 343.09691146, 332.8292643 ,
       373.93144771, 350.36578276, 355.02604311, 391.00527889,
       371.2364958 , 324.07275202, 370.36182491, 373.41536354,
       368.05543264, 332.63171135, 383.07463228, 382.48332959,
       318.16067052, 359.33219683, 357.27887404, 382.27899363,
       376.93497597, 322.50416117, 319.36743508, 357.08868659,
       410.3591328 , 323.26753342, 317.55094796, 323.20836914,
       352.25148078, 400.27268197, 333.55869903, 369.52666291,
       369.54028381, 387.46494136, 404.13297058, 313.49978396,
       384.60071146, 318.73643315, 359.39276948, 321.82919224,
       339.05850553, 345.74690899, 386.88439986, 375.99779231,
       350.17188352, 319.22645444, 365.25037252, 401.57990248,
       324.30656837, 368.32764375, 375.57652192, 337.85391373,
       340.92546875, 352.84568883, 323.14471437, 382.67540205,
       390.23388863, 365.48174948, 327.8634042 , 328.28822417,
       374.02008775, 399.81131469, 374.32700902, 349.763363  ,
       359.45953296, 348.43938064, 327.54443679, 325.57314892,
       386.05276534, 326.10159536, 400.14139567, 329.12136115,
       342.64619624, 340.06717673, 356.21979477, 325.79291717,
       332.2661615 , 330.69765844, 355.61211713, 332.31892799,
       353.20853439, 388.89302045, 322.99231127, 352.1411708 ,
       378.31012501, 398.00306161, 334.1280958 , 396.79969963,
       378.89326928, 399.89521161, 374.34393288, 357.41796292,
       401.51489544, 368.06313336, 341.44933592, 358.97643636,
       369.46590535, 322.72556055, 334.9533092 , 387.13450315,
       355.71861991, 332.56637121, 379.03918619, 343.5606739 ,
       359.68760747, 394.41416169, 350.35060294, 333.91958273,
       336.86280328, 354.02957323, 355.75267961, 330.1326514 ,
       398.87761206, 381.94244425, 364.32432014, 348.71797532,
       371.8617229 , 403.5621917 , 397.80483117, 392.32789026,
       384.32137962, 388.83540947, 377.48010196, 384.68665143,
       322.34736481, 338.14670886, 328.76805395, 369.7126372 ,
       317.86268458, 376.45881496, 330.27818557, 387.45036448,
       389.61014158, 399.93966279, 321.71885282, 379.71387114,
       336.70551516, 381.33788149, 363.55176559, 380.42008728,
       392.61481966, 334.06000919, 353.04198742, 358.72805606,
       408.32883985, 334.75567113, 316.10217758, 393.84976499,
       373.06212706, 324.25121677, 380.12336956, 356.18285442,
       369.23220683, 318.71698185, 315.15620512, 328.29422596,
       327.56484332, 319.86600361, 394.2791925 , 337.06779681,
       367.14181221, 349.96340982, 342.87430127, 356.93354911,
       351.52591129, 384.51452345, 364.68520663, 322.43019006,
       322.51774727, 365.64148156, 321.40837103, 406.15912949,
       371.51854255, 319.9488823 , 318.57840994, 327.31574255,
       318.79295095, 369.69866267, 350.1673161 , 327.21685975,
       333.58532996, 319.79860912, 349.8583988 , 338.20620817,
       336.69080001, 361.31315361, 363.21605244, 408.75302519,
       337.70524922, 329.61905595, 325.55520252, 379.77256359,
       353.80153339, 362.42258588, 321.2446487 , 382.35835602,
       352.97697785, 317.71794398, 396.99707007, 377.50623096,
       317.91668772, 333.27090713, 317.06352504, 369.87110417,
       354.00247291, 362.00392965, 348.8287582 , 317.36831365,
       350.04545673, 380.78495583, 347.24430241, 337.80825787,
       317.97717167, 347.08027692, 386.03434362, 356.41517947,
       338.37068442, 326.83406573, 409.45058049, 393.06751013,
       367.84827292, 409.15216681, 370.59576306, 338.14313689,
       382.52878072, 378.39070727, 404.07221805, 328.76466011,
       360.70392112, 398.93525102, 366.88416728, 318.8588087 ,
       360.16216156, 376.10058895, 338.3358826 , 315.79248226,
       346.98961438, 364.97256477, 327.49862446, 341.65743104,
       330.80477278, 356.38982738, 354.89000835, 369.06067342,
       344.42238754, 341.56237805, 398.50905278, 324.08560078,
       398.69878932, 323.97927513, 353.98008227, 322.09839447,
       365.20022369, 343.1849753 , 331.57499169, 363.01254968,
       325.21849661, 390.22447641, 314.96747089, 404.44496511,
       320.2125786 , 322.16673981, 336.14050529, 360.87157877,
       318.70185235])

In [20]:
LinReg.score(x_train,y_train)

0.9986131755816301

In [22]:
input = [[181, 1958.292, 317.45, 315.29, -1]]
ans = LinReg.predict(input)
ans

array([317.71794398])